### ISSUE TITLE
Background image not changing with weather

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#103]
I haven't looked into the logic, but the weather is not correctly reflected in the background image.

Should we consider adding a textual description of the weather as well? As far as I know this is provided by openweathermap.

**Comment by BorisKingma** [comment]
there is no logic implemented yet.

the textual part is "nice to have" now.

the feedback part is must-have.



Op vr 3 mei 2019 11:04 schreef Henriette Steenhoff <notifications@github.com

**Comment by Chuansi-LU** [comment]
1. when the thermal stress is minus (blue or light blue), the advice dot is also blue, the colour contrast is not very clear. The dashbooad backgroud colour or thermal stress (Cold side) could be adjusted.  
2. the dot size could be bigger.

**Comment by frksteenhoff** [comment]
Cannot comment code for rain MP4 back in before I have the actual file

**Comment by frksteenhoff** [comment]
Textual description added with 3898474a202b4b4ed362045e2c26aa9fb4cd7c61, background image under development, closing.
