### ISSUE TITLE
Increase support of learning process

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#108]
**What is the learning process?**
*The learning process* refers to how the user is introduced to and supported in unerstanding how the app works, how to interpret the information provided and learns to change behaviour from its content.

**Ideas to support learning process**
* Implement introduction/walk-through of modules on first login (Henriette working on it in branch `dev_heste_intro`
* Give basic information to users in beginning (added)
* Move on to more detailed information as user gets to understand the basic workings of the app (need more information on this logic)

**Comment by frksteenhoff** [comment]
Current idea for introducing the user to the app on first login:
* Go through the different panels in the app and give brief descriptions of the different information provided, i.e:
   * Show Dashboard panels top panel, tips panel, activity level one by one when one panel is shown the rest are faded. The area that is being described is highlighted and accompanied by a tooltip description.

Shown in the flow below:
![image](https://user-images.githubusercontent.com/6978512/57850292-dcf48180-77dd-11e9-849d-4c016d5ae04e.png)

**Comment by Chuansi-LU** [comment]
Nice to give support for users to learn ClimApp. I think usually new users find it difficult to use and understand. After having used for a couple of times, users may look for more detailed information and advice. 
A few comments and suggestions:
1. Need also to introduce "Advice, adaptation/coping strategies" to guide users on how to take actions (change behavior) if there is a warning. At the moment, the ClimApp focuses on "warning". It may give new users an impression that ClimApp is just another weather app.
2. Coping strategies such as work/rest scheme (e.g. 75% work, 25% rest), hydration (200 L/h), cooling suggestions (seeking shade, use of fans, ventialtion clothing) in the heat, protection again cold (e.g. required clothing clo, extremity protection) should be included. These coping strategies should be described in more detail than general descriptions.
3. If possible, design 1-3 levels of details of advice for new usuers, experienced users, expert users (e.g. for analytical and educational purpose).
4. Provide possibility to allow users to input local microclimate data, metabolic rate data, if available/measured locally. 
5. Not much personal information is used at the moment in the app. Acclimatization to heat is an important individual factor. Acclimatization is included in both WBGT and PHS standards.

**Comment by frksteenhoff** [comment]
Hi Chuansi, 
I agree on the the understanding the content within the app (we need more guidance which is why I am working on the introduction module), however I do feel like the navigation part should be easy to grasp, please let me know exactly what you find challenging if you feel differently.

1. We are working on getting more advice/adaption strategies however this requires a lot of thought into which scenarios to show the different information which is something that is still being developed.

2. I think this related to the first question, the same answer goes here.

3. Currently we are working with 2 level beginner and experienced user.

4. This is something I have started working on it locally (not available yet) in a new branch (to resemble that of the Android version I made for you last year, however this is not currently a priority).

5. I asked @BorisKingma whether we should include this earlier and as far as I am aware the model that he now has implemented does not take this into account as the earlier model in the Android version did.

**Comment by Chuansi-LU** [comment]
Hi Henriette,

I agree that it is not easy to establish the rules of applying the advice/coping strategies. A few more thoughts/feedback:


1.       I tried “Feedback” under Settings, and still got “something went wrong at: 107” (for iPhone).


2.       I noticed that wind speed in Lund today at 10 m was about 12 m/s, but Dashboard gave a wind speed of about 1.4 m/s at 2 m height. I think the difference (12 vs. 1.4 m/s) should not be so big.


3.       Weather report now shows current weather (better than before).


4.       Is indoor climate prediction and PMV (thermal comfort) implemented?


5.       The 5 activity intensities are highlighted on the Dashboard. In a same weather condition, if a user changes activity from rest to intense, a more likely scenario would be to allow the user to change corresponding clothing as well. It is very unlikely, the user will wear the same clothing for all 5 activities. As Boris mentioned, this is something to be considered in next update.

Best regards,
Chuansi

**Comment by Chuansi-LU** [comment]
I replied through email and copied it below:

I agree that it is not easy to establish the rules of applying the advice/coping strategies. A few more thoughts/feedback: 

1.	I tried “Feedback” under Settings, and still got “something went wrong at: 107” (used iPhone).

2.	I noticed that wind speed in Lund today at 10 m was about 12 m/s, but Dashboard gave a wind speed of about 1.4 m/s at 2 m height. I think the difference (12 vs. 1.4 m/s) should not be so big.

3.	Weather report now shows current weather (better than before).

4.	Is indoor climate prediction and PMV (thermal comfort) implemented? 

5.	The 5 activity intensities are highlighted on the Dashboard. In a same weather condition, if a user changes activity from rest to intense, a more likely scenario would be to allow the user to change corresponding clothing as well. It is very unlikely, the user will wear the same clothing for all 5 activities. As Boris mentioned, this is something to be considered in next update.

**Comment by frksteenhoff** [comment]
Yes I will allow myself to delete one of the copies to minimize duplication. I will reply to your points tomorrow or during the weekend. 

Edit:
After we made the Cordova version of the app, all weather related implementations are made by and developed by Boris, so I believe it would be better if he replied.

**Comment by BorisKingma** [comment]
Hi Chuansi, Henriette,

response to the points, and some extra to think about.

1. @Henriette Steenhoff <henriette.steenhoff@gmail.com> - feedback lin 107
this one is solved in next version right?
2. in current development version windspeed at 2m is calculated according
to  va_2m = va_10m * Math.pow( 0.2, 0.25 ); //stability class D Liljgren
2008 Table 3
-- for your example that means 2m in next update would be 8m/s.
3. current weather = current weather at timestamp of request.
4. PMV model is not yet used (it is available though). We cannot use it for
outdoor, and for indoor we have not decided whether we want to predict the
indoor environment, or let the user fill it in.
5. In my opinion the lowest activity class should be removed. - a clothing
selection is required for ISO 7243 effective WBGT correction. My proposal
there comes down to have 4 textual options, not icons. Icons are
troublesome with respect to diversity, and text seems to have this issue
to.a lesser extent.

6. acclimatisation is required both for PHS and WBGT and must be re-added.
For WBGT it affects the RAL equation to be used and for PHS it affects the
thermoeffector response.

7. an issue not covered now is the discontinuity in Climapp score. In this
season it is apparent for cool days from medium to high activity level IREQ
< WBGT/RAL and WBGT/RAL < 0.8, which means that we are in green positive
heat stress scale for all these activities. For low activity level IREQ >
WBGT/RAL and IREQ > 1 makes the gauge jump to light blue, which feels a bit
weird from user perspective. We need a more continuous rule/function to
cope with this. Ideally ofcourse only 1 index for both hot and cold
conditions.

From that perspective - how about using DLIM (duration limitation) for the
gauge. We calculate DLIM both for IREQ and PHS, a low DLIM means a high
heat stress / cold stress. I know it is quite a step from our WBGT/RAL
approach, but I also think it is good to keep an open mind on how we define
the gauge value.

8. The mean radiant temperature. I worry the Kruger 2014 implementation
highly overestimates Mean Radiant Temperature. I tested it with the Lund
PHS site and we get the same result, so I do not think it is an
implementation issue. Please follow this issue with me.

9. with respect to cloudlevel and globe temperature. I have now implemented
a WBGT_clouds value which uses the Liljgren method, yet the solar radiation
is scaled with cloudiness such that 100% cloudiness blocks 80% of direct
solar radiation ( 20% remains and greatly reduces globe temperature ). Yet
it is not yet used in Climapp. Please let me know if you think we could use
this approach.

10. I just realised the Liljegren calculated globe temperature is a 5cm
globe, not a 15cm globe, this we will have to take into account.

11. how should we address rain and/or snow?

kind regards,
Boris

**Comment by Chuansi-LU** [comment]
Hi Boris,
good points!
2.  windspeed at 2m is calculated according to  va_2m = va_10m * Math.pow( 0.2, 0.25 ); //stability class D Liljgren 2008 Table 3. 
For D class, should the Power be 0.25 and 0.15?

4. PMV: we need to discuss this with Jorn. according to his report, it is possible to predict Indoor climate, but of course, need to input building information by users. To directly input Indoor Climate conditions is another way, but users usually do not have all Indoor Climate data (Ta, RH, air velocity, Tmrt).

5. Re: Remove lowest activity level: The lowest level is relevant to Indoor situations, e.g. resting Indoors (sitting and resting on a sofa on a hot summer day. Yes, clothing is also included in the latest version of WBGT. Clo input is needed for all body heat balance models: PMV, PHS and IREQ.

6. Need to apply both eqations: Recommended heat stress alert limits (RALs) for unacclimatized workers, Recommended heat stress exposure limits (RELs) for acclimatized workers. 

7. In the above equations, how many minutes/h can be exposed are also available in Figures 8-1 and 8-2 (US CDC/NIOSH recommendations). Using limit exposure time as the gauge indicator can be a good idea. Alternatively, total body heat storage/loss (W or W/m2) based on heat balance equations can be converted into a continous scale, .e.g -40 W corresponding to col stress -0.5. alternatively use a category scale rather than a coninuous scale?

8. Here are more references for Tmrt calculations:  Krzysztof Błażejczyk (2014), Andreas Matzarakis (2010), Fanger PO, 1970. There is a relevant document describing how Tmrt is dealt with for UTCI index at: http://utci.org/utci_doku.php

9. Jorn presented a method a year ago. I am not sure if it is the same approach as Liljegren. We can ask Jorn. Krzysztof Błażejczyk (2014) used the following approzimation (Tg is temperature of ground surface approximated as follows): 
for cloudiness >= 80% - Tg = Ta
for cloudiness < 80% and Ta >= 0°C - Tg = 1.25·Ta
for cloudiness < 80% and Ta < 0°C - Tg = 0.9·Ta

10. Yes, I Think the correction is available.

11. rain and snow are not dealt with in those models. I Think we just need to add some simple advice, e.g. if it is raining,  "wear rainproof/rain clothes". If snowing, add "snow may melt and wet your clothing, use waterproof clothing", etc.

**Comment by frksteenhoff** [comment]
Hi Boris, 

1. Yes the error Chuansi is experiencing should be fixed from the next update we make. 

4. We have the possibility of using a prediction model from one of Jørn's phd students. 

5. We can discuss this when you come to Copenhagen?

6. I will implement this right away.

7-11 not relevant for the learning process, more the user experience of the app.

9. Would it be possible to also pass the cloudiness value as a parameter from server to app? (would be nice to also include this) + it would be great also to have the textual description of the weather.

**Comment by frksteenhoff** [comment]
Implemented introduction as part of f17969de260b6b2c270c70ea96ef899aec3abecc
