### ISSUE TITLE
adaptation adjustment

### ISSUE THREAD

**Issue by BorisKingma** [frksteenhoff/ClimApp#118]
**Describe the bug**

1. filled in adaptation score, from 1 to 0.5: -0.5  is processed correctly. 

2. Afterwards I filled in adaptation score again (now from 0.5 to 1 again (+0.5)), and this is not processed correctly, the value on gauge becomes 1.5 instead of 1.

adaptation adjustment is currently the delta in the feedback module as:
Delta = User value -  adjusted model value 

the value of delta should be:
Delta = User value - Unadjusted model value

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frksteenhoff** [comment]
Closing after testing the newly implemented logic -- please reopen if logic is different than expected.
