### ISSUE TITLE
Push Notification plugin

### ISSUE THREAD

**Issue by BorisKingma** [frksteenhoff/ClimApp#122]
Hi Henriette

https://www.npmjs.com/package/cordova-push-notifications

push notifications are required to be able to send notifications - requires setup of GCM for android and Apple APNS for iOS.

**Comment by frksteenhoff** [comment]
Ah, of course! This might not be something that I can get working on before after thesis hand-in, but let's see how much time I got.

**Comment by frksteenhoff** [comment]
However, what we want **is not** to *send notifications from a remote server*, but rather to send notifications *locally from the same device that will receive the notifications*, so I don't believe this will solve anything. 

This framework is for a different use case.

**Comment by BorisKingma** [comment]
cant we just schedule a calender event? like we set our 'wake up' alarm?

Op vr 5 jul. 2019 10:49 schreef Henriette Steenhoff <
notifications@github.com>:

**Comment by BorisKingma** [comment]
as per meeting 8th of july, we agreed that push notifications from external server is good to go.

I will keep the issue open - to be closed when it is implemented

**Comment by frksteenhoff** [comment]
I cannot create an overview of when to send notifications without us agreeing on framework, whether to have individual notifications and the general use cases where we find it useful.

**Comment by Chuansi-LU** [comment]
A suggestion: an easy criterion to send Cold/heat stress notification is to use the Thermal Stress alert score, <-2.0 and >+2.0 as threshold.

**Comment by BorisKingma** [comment]
i have a strong inclination to propose only to use global notifications,
that is, all users via 1 message.

personal notifications will trigger too often with simple rules -- or
mistakes at settings on user end, leading to end-user annoyance and total
ignoring of notifications.

for this phase (user testing in winter) we cannot allow that,  with only
global notifications to ask users to fill in a questionnaire on usability i
think we maximize utility and can maximize user feedback.

too many notifications destroys more than we wish to achieve.

regards

Op vr 20 sep. 2019 16:49 schreef Chuansi-LU <notifications@github.com>:

**Comment by BorisKingma** [comment]
implemented in v3.01
