### ISSUE TITLE
DTU server does not provide App ID

### ISSUE THREAD

**Issue by BorisKingma** [frksteenhoff/ClimApp#127]
<img width="888" alt="Screen Shot 2019-08-10 at 8 34 11 PM" src="https://user-images.githubusercontent.com/12566222/62825576-5bc74380-bbae-11e9-8efd-47a799274438.png">

**Describe the bug**
after user create - dtu server returns empty string

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frksteenhoff** [comment]
I believe you might have made a typo, it should be a `&` rather than a `?` separating the `user_id` and the API call -- and you need need to specify the parameter `user_id`.

![image](https://user-images.githubusercontent.com/6978512/65685686-d8c95200-e062-11e9-9d80-35c43eef86f2.png)
