### ISSUE TITLE
Units selection

### ISSUE THREAD

**Issue by FritzdorfSport** [frksteenhoff/ClimApp#145]
**Describe the bug**
Units don't appear correctly in Preferences

**To Reproduce**
1. Tap the Cog icon
2. Tap Units at the top

![IMG_9396](https://user-images.githubusercontent.com/10878963/90238889-f47a4a00-de26-11ea-8e01-83fb2edc843d.png)

**Smartphone (please complete the following information):**
 - iPhone7
 - iOS 13.6

**Comment by BorisKingma** [comment]
brr... i'm on it.

**Comment by BorisKingma** [comment]
the module does not support special characters- I have spelled-out Celsius and Fahrenheit instead
