### ISSUE TITLE
Forecast - Measure I Hydration

### ISSUE THREAD

**Issue by FritzdorfSport** [frksteenhoff/ClimApp#149]
Tap Forecast

to get more personal, detailed, "scientific" information, 

except when you scroll to the bottom, the advice in "Measures" and "Hydration" is not personalised, is general, and may not be relevant to the situation or person.

It feels out of place here.

**Comment by Chuansi-LU** [comment]
When I noticed "Measures" and "Hydration" the first the time, my impression was that the colour does not seem to match the colour of the app. The more I use the app, I feel more information it provides to users (the app itself actually does not provide much advice). I agree these two buttons do not provide perosonal and situation specific advice. A solution is to change them to "General Measures", "General Hydration Advice", perhpas? I am thinking to design similar infographics for Cold stress.

**Comment by BorisKingma** [comment]
new version - 
infographics will be under general info. for now only heat infographics are present.
after cold infographics are available they can be added as well (to provide info in when it is colder)
