### ISSUE TITLE
Predicted indoor temperature

### ISSUE THREAD

**Issue by FritzdorfSport** [frksteenhoff/ClimApp#150]
The Predicted indoor temperature never calculates.

1. Tap house icon at bottom
2. Choose to use indoor mode

![IMG_9397](https://user-images.githubusercontent.com/10878963/90240319-4d4ae200-de29-11ea-8d5c-129d1b1edd2f.png)

iPhone7
iOS 13.6

**Comment by Chuansi-LU** [comment]
I come across this issue a number of times. But sometimes it calculates (a bit unstable). Another issue is the predicted Indoor temperature is 21  (when Thermostat is 3), 23 (when Thermostat is 1-2). The Indoor temperature prediction does not seem dependent on windows (open or close).

**Comment by BorisKingma** [comment]
The indoor module works - however the predicted indoor temperature is not always received. The new UI will show more focus on the user selected indoor temperature, and show the predicted indoor temperature as a suggestion
