### ISSUE TITLE
WBGT reference values and colour coding

### ISSUE THREAD

**Issue by Chuansi-LU** [frksteenhoff/ClimApp#23]
Both US NIOSH RAL limit values and ISO WBGT reference values indicate the threshold between two zones: Green and Red. Green zone indicates that the majority of workers can work 8-hour shift with core temperature not exceeding 38.0 C.

Lars suggested Dividing zones into: Green<80% RAL, Yellow 80-100% RAL, Red 100-120% RAL, Dark Red >120% RAL. 

I have tried to calculate Lars four-colour coded zones (green, yellow, red, dark red). Let’s assume a moderate metabolic rate 349 W, for unacclimatised persons, we use equation RAL [°C-WBGT] = 59.9 − 14.1 log10 M [W] (this is exactly the same equation used in ISO WBGT), the RAL limit value (for 60 min continuous work per hour) is 24.0 C. This is ISO WBGT reference value (threshold value). It means unacclimatized workers can work continuously 8 hours when RAL < 24.0 C (green).

According to Lars 4-colour code zones, we will get these ranges:
Green zone 80% RAL < 19.2 C, 
Yellow zone (80-100% RAL): 19.2 – 24.0 C, 
Red zone: 24.0 – 28.9 C, 
Dark Red: >28.9 C.

It is in agreement with US NIOSH and ISO method to use Red zone (> 24.0 C. I am not sure if Dark Red zone is needed in this case). but problem is it will alert heat stress already at 19.2 C, much lower than the ISO threshold value 24.0 C? The yellow zone alert is not in consistent with NIOSH and ISO standard. It may be useful for vulnerable Groups like the elderly. We need to discuss and find literature to support the division of 4 color zones. It seems that 90%, 100% and 110% division is more reasonable than 80%, 100% and 120% mothed (but it is also arbitary).

**Comment by Chuansi-LU** [comment]
In the “heat module”, PHS and hydration modules are also included in addition to WBGT. WBGT is an important screening heat index with a focus on environmental factors. It has limitations. NIOSH RAL does not take into account clothing effect. WBGT does not provide estimation of water loss and body core temperature change. For further analytical determination and interpretation of heat stress, we need to add the calculation of the predicted heat strain (PHS).

**Comment by frksteenhoff** [comment]
WBGT and RAL is implemented with help from Jørn and Lars.
