### ISSUE TITLE
Possible Interface improvement: as weather info (input) is shown on the top. Activity level like clothing is also an input parameter. Perhaps it is more logic to move Activity Level up (input) and move Warning and Advice (outputs) down, or as a separate Warning and Advice page.

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#28]
Converted to issue in order to start discussion

**Comment by frksteenhoff** [comment]
Great input. The reason why I have chosen to place the outputs above the inputs is that is will be easier for the user to get a full overview "at-a-glance" without having to scroll down to the advice.
Clothing will be in its own pane as it is can end up becoming a much more complex setting to configure for the user.

**Comment by FritzdorfSport** [comment]
A huge positive of last week's meeting was that the developers were given more power/freedom/mandate to make these kinds of decisions without having to obtain agreement from the whole group.
