### ISSUE TITLE
Good suggestion for suggestions!

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#29]
It would help to demonstrate ClimApp for participants during our Theme Day on Monday, 29 October in Lund, if the input of latitude/longitude function could be added.

**Comment by frksteenhoff** [comment]
I have made a version with possibility of exploring lon/lat pairs. It will not be published on Google Play, I will send you the APK (application package) then you can open the file from a compatible device.
I have chosen to do it this way as the time to implement and test this has been very limited and because the solution needs more work before I find it production ready.

**Comment by Chuansi-LU** [comment]
Ok, look forward to the application package.

**Comment by frksteenhoff** [comment]
Mail sent to Jakob and Chuansi
