### ISSUE TITLE
Generate privacy policy and terms of use

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#3]
Need to make sure that the privacy policy and terms of use matches the group's expectations.

**Comment by FritzdorfSport** [comment]
Hej Henriette,

I don't know if this is the help you are looking for, but this seems to be a question about how much access to the individual's data we should ask for/demand.

In my opinion: our goal is to be able to give as many users as good an experience as possible. For that reason, all features should be accessible to all users all of the time, whether they give permission for us to receive their personal information/data or not.

Therefore, the App should have as many features as possible that are native on the user's device, which also means that all of the user's data should be stored on their device. Access (for us) to all of their data should be the default setting on installation and mentioned in the Terms of use, and the user is allowed to opt out of this. If they opt out, they will still have a fantastic experience.

**Comment by frksteenhoff** [comment]
Thank you so much, Stephen. I was thinking that I would make a first draft, but I am not sure whether this would be relevant before working on the actual app. Either way I think it would be good to have some sort of basis to build on top off.

**Comment by FritzdorfSport** [comment]
I am not sure the formal T&Cs need to be written today. 

But, like you say, you need a basis to build on - especially when it comes to where the data are kept. Would be quite difficult to design the App otherwise :-)

**Comment by Chuansi-LU** [comment]
I agree with both of you, Stephen and Henriette.
Where will users' data (e.g. age, body weight, height, BMI) be stored, on their mobile phones or on the server?

**Comment by FritzdorfSport** [comment]
Hej Henriette,

Is this still a "Help wanted" item? If so, please let me know how I can help further.

**Comment by Chuansi-LU** [comment]
Hej Henriette,
I hope your study is going well in 2018. We will have Swedish partner meeting on 17th of January, between 15:00-16:00. Do you have time to join us via Skype? Stephen would like to discuss with you about "Help wanted" items in GitHub.
Best regards,
Chuansi

**Comment by frksteenhoff** [comment]
Hi Chuansi and Stephen, 
The task is no longer help wanted, I got what I needed thank you.

In the end I am hoping that the user data is stored on a server, but for the prototype storing data on the individual device will suffice.

I have just answered you mail regarding the meeting Chuansi. I think we should plan for another meeting, as I am unable to attend today due to studies.

**Comment by frksteenhoff** [comment]
Current terms and conditions - based on generic template, was made as a 1st draft since the app needs this in order to be accepted on Google Play. https://privacypolicies.com/privacy/view/cccfc859c42cbe1295b46869a4f81618

Uploading a new terms and coditions is not a problem, but we need someone with the proper legal insights to do it.

**Comment by Chuansi-LU** [comment]
I asked our legal counsel at LU. He said when the app is not collecting users' data, there is no big issue. thus, "Information Collection And Use" does not seem to apply the app at present stage? 
Once we collect and store users' data, then there is a concern in relation to the new general data protection regulation in EU.

**Comment by frksteenhoff** [comment]
You are right Chuansi, but as the database gets connected to the app, there will be stored data that can be traced back to the individual user (only though a global device ID -- it will take anyone quite some work to figure out who the device belongs to, but it is not impossible). It might not be there right now, but instead of having the user's believe that we are storing no data and suddenly having them find out that we do, I thought it would be best to add it already.

**Comment by Chuansi-LU** [comment]
I see. I will ask our legal counsel at LU for help. Perhaps Jörn can also ask the legal advisor at DTU.
