### ISSUE TITLE
Setup sqlite3 database integration with local database

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#33]
* [x] Create local database  
* [x] Create ER diagram for database (based on current understanding of what is needed)
* [x] Create database schema
* [ ] Connect app to database
* [x] Generate and store UUID in app 
* [ ] On *trigger* send user data to database (key: `UUID`, values: `temperature, humidity, activity level, wind speed` (user info in other table?)
* [x] Handle possible missing data (when/if user has not disclosed any personal information)

*When this is working, move to distributed database*

**Comment by frksteenhoff** [comment]
Jørn is working on setting up a server on DTU to host the database

**Comment by Chuansi-LU** [comment]
Great! It is good to receive feedback and comments from different users. Gradually there will be more and more users to download and install ClimApp. We have been promoting it at a number of events. 
On our Therme Day (29 Oct.) in Lund, about 5 participants who have Android phones installed and tried the app.

**Comment by frksteenhoff** [comment]
When using the MySQL database, the sqlite3 database is obsolete. The data we want to store in the app can easily be stored to shared preferences. Closing issue.
