### ISSUE TITLE
Find thesis advisor (besides Jørn) from DTU Compute

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#35]
**Areas**
UX, AI/ML, Software Development, Learning Analytics

The thesis has to fulfil the criteria for a [Digital Media Engineering thesis](http://sdb.dtu.dk/2018/35/697): 

**Possible advisors**
* Helle Rootzen - learnT, Learning Analytics, motivation for learning, educational data mining
* Per Bækgaard (study line advisor)
* Jakob Eg - Human Computer Interaction, user testing, design
* Mikael Kai Petersen - UX, microinteractions
* Anders Roy - computational tools for data science (only if we have a lot of data > 1.000.000 rows)

**Upcoming tasks**
* [x] Talk to Helle about possibilities (meeting scheduled November 14th)
* [x] Set up meeting with Per Bækgaard to explore possibilities (will try him at the office November 14th)
* [x] Setup meeting with Jørn and possible advisor to pan out how the thesis will proceed and what to focus on (mail sent Nov 29)
* [x] Send mail to Per answering questions about: **state-of-the-art**, **what will the thesis encompass** (what will be investigated, what will be implemented), **outcome** (what is it exactly that we want out of it, an app, a paper, data for someone to use)

**Comment by Chuansi-LU** [comment]
If there is a need and if it is possible to have external advisors, there are teachers at LU in the area of interaction design and usability. In The Netherlands, Boris Kingma has experience in developing apps.

**Comment by frksteenhoff** [comment]
Thank you Chuansi. I do believe I need a more technical advisor, but if that is not the case I will take you up on your offer 😊

**Comment by frksteenhoff** [comment]
Chosen advisors:
* Jørn Toftum (main advisor)
* Per Bækgaard 
* Jakob Eg Larsen
