### ISSUE TITLE
Create timeline

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#44]
Timeline for the **ERA4CS ClimApp project, WP2** development in 2019 with overview of how tasks are split between @BorisKingma and @frksteenhoff 

**TODO**
* [x] Agree on content (01-03-2019)
* [x] Convert tasks into issues  (all but reminders)

| Month/milestone | Task (+ issue no) | Responsible | Label |
|---|---|---|---|
| **February 2019** |  |  |  |
|  | **Reminder:** Milestone 1, final report, WP1  |  | WP1 |
|  |  Integrate PHS, IREQ, WBGT, PMV and windchill in Cordova app + add forecast data | @BorisKingma  | development, loosely related to #31  |
|  | Setup of server and development of database, API and extended logic in Android app for database communication |  @frksteenhoff | decision, development, related to issue #36  |
| **March** |  |  |  |
|  | Decide upon how to store data from previous day |  | decision, related to issue #45 |
|  | Change sensationmapps (smaller steps between grid points) | @BorisKingma |  decision, development |
|  | **Reminder:** Deadline for ICEE conference abstract |  | other |
|  | Development (visualization) of logic for model output (part of knowledge base) + excel file with advice and thresholds | @BorisKingma, @frksteenhoff   |  decision |
|  | Implementation of logic for model output (part of knowledge base) | @BorisKingma, @frksteenhoff   | development  |
|  | Publish Cordova app to Android/iOS closed beta testing (15th of May) | @BorisKingma | release |
|  | Design new dashboard layout for ClimApp (based on output from all models)  | @frksteenhoff   | design  |
|  | Decide upon how we show feedback questions (static or dynamic) | @frksteenhoff   |  decision |
|  | Implement feedback module in Cordova app  | @frksteenhoff   | development, related to issue #40  |
|  | Hand in documentation of database setup to Jørn (23th of March) | @frksteenhoff   | documentation |
|  | Align logic in Android and Cordova app in order to phase out Android version  | @frksteenhoff  |  development |
|  | Migrate database logic from Android app to Cordova app | @frksteenhoff  | development |
| **April** |  |  |  |
|  | **Deadline** for ICEE conference abstract |  | other |
|  | Discussion of hydration logic and how to integrate in app with @FritzdorfSport (hopefully in March already)  | @frksteenhoff + Jørn | decision related to issue #26  |
|  | Implementation of hydration logic | @frksteenhoff, @BorisKingma | development |
|  | Find user group to test with, help from @Nybo72? | @frksteenhoff  | decision, planning  |
|  | User testing of dashboard for ClimApp | @frksteenhoff   |  user test |
| **May** |  |  |  |
|  | **Reminder:** Quarter report 1, WP2  |  | WP2 |
| | Create basic setup for scenario playground, select for detailed input on PHS, IREQ (decide on architecture and integration with database)  |   | decision, development |
|  | Test scenario playground with users  |  @frksteenhoff  | user test | 
|  | @BorisKingma in Denmark (23-24th of May)  | | | 
|  | Cordova version of app ready to be published in App Store/Google Play  |   @BorisKingma , 
| **June**  |  |  |  |
|   | Presentation for ICEE | @frksteenhoff |  |
|  | Test period to validate ClimApp with user group, 2 weeks | @frksteenhoff   | user test  |
| **July** |  |  |  |
|  | [ICEE conference Amsterdam](https://www.iamsterdam.com/en/business/meetings/calendar/event/icee-2019-international-conference-on-environmental-ergonomics) (7-12th of July) | all | other |
|  | Finalize thesis before hand-in |  @frksteenhoff  | documentation  | 
|  | Henriette hand-in of master thesis (30th of July) |  @frksteenhoff  | other | 
| **August** |  |  |  |
|  | **Reminder:** Quarter report 2, WP2  |  | WP2  |
|  | Henriette thesis defence (hopefully first week of August) |  @frksteenhoff  | other | 
| **September** |  |  |  |
|  |  |  |  |
| **October** |  |  |  |
|  |  |  |  |
| **November** |  |  |  |
|  | **Reminder:** Quarter report 3, WP2  |  |  WP2 |
| **December** |  |  |  |
|  |  |  |  |
| **January 2020** |  |  |  |
|  |  |  |  |
| **February** |  |  |  |
|  | **Reminder:** Quarter report 4, WP2  |  |  WP2 |
|  |  |  |  |
| **March** |  |  |  |
|  |  |  |  |
| **April** |  |  |  |
|  |  |  |  |
| **May** |  |  |  |
|  | **Reminder:** Quarter report 5, WP2  |  | WP2  |
|  |  |  |  |
| **June** |  |  |  |
|  |  |  |  |
| **July** |  |  |  |
|  |  |  |  |
| **August** |  |  |  |
|  | **Reminder:** Milestone 2, WP2  |  | WP2  |
|  |  |  |  |

**Comment by Chuansi-LU** [comment]
Row #2: please keep in mind PMV for Indoor Climate too.

**Comment by frksteenhoff** [comment]
All task created in project board https://github.com/frksteenhoff/ClimApp/projects/2
