### ISSUE TITLE
Mapping of model output to textual advice (part of knowledge base)

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#49]
Different suggestions have been made. Some examples shownin issue #40 by @frksteenhoff

**Comment by frksteenhoff** [comment]
Partners currently working on extending the following rules (from email by Boris 15th of April): 
![image](https://user-images.githubusercontent.com/6978512/56560653-531e1380-65a5-11e9-9b7b-be351182e9d0.png)

**Comment by BorisKingma** [comment]
this is fixed via thermaladvisor.php layer
