### ISSUE TITLE
Decide upon back-end provider for user data

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#5]
For the prototype I will not be saving user data to an external source, but rather keep it on the phone.

**Comment by Chuansi-LU** [comment]
It can avoid pravicy issue. But we will not be able to get feedback from users and we don't know how many users are using the App, and who they are, etc.?

**Comment by FritzdorfSport** [comment]
For the prototype, I think it is OK for us not to collect data from the users. Of course, it is something that should be built into a later version.

Perhaps a quick way to implement that in the 2nd version would be to add a "Send Feedback" button, that sends an email. Another possibility for a later version is to add some Analytics that record how often the App is opened and for how long. These could be two steps along the way to collecting personal data that require permission from the user.

**Comment by Chuansi-LU** [comment]
A good surprise to get Quick feedback on my comment :)

Agree.

**Comment by frksteenhoff** [comment]
@FritzdorfSport as an Android developer you get a dashboard for each of you app showing both average time spent and how many that has downloaded the app (type of android phone, version of android etc.) and which version they each have installed.

**Comment by frksteenhoff** [comment]
Chosen provider:

MySQL database on DTU Byg server
