### ISSUE TITLE
Publish Cordova app to Android/iOS closed beta testing (15th of March)

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#51]
Implementation specific
* [x] App does not get data on Android rather NaN. (early error)

Release related
* [x] Remember to set `firstLogin` to `true`
* [x] Remember to set `hasExternalDBRecord` to `false`
* [x] Make Android build ready for Google Play. Available here: https://play.google.com/apps/testing/com.climapp.app
* [x] Make iOS build ready for Apple Store

**Comment by frksteenhoff** [comment]
I think it would be good if we made some sort of procedure for feedback rather than receiving a lot of different emails that we would need to keep track of. 

It would be nice to use GitHub, but there is a little barrier to entry compared to just sending an email.

Making a questionnaire might make it a little too formal or standardized such that people might forget some aspect of their testing they had comments to or don't include it because the questionnaire does not leave room for it. Do you have any suggestions?

**Comment by frksteenhoff** [comment]
List of testers: 

https://github.com/frksteenhoff/ClimApp/blob/dev_henriette/Conceptual%20drawings/testers/climapp-testers.csv (please update if not correct)

Furthermore, we should streamline the promotional content related to the app and the preview screens (before actual alpha release).

**Comment by BorisKingma** [comment]
ios ready -
