### ISSUE TITLE
Discussion of hydration logic and how to integrate in app with @FritzdorfSport (scheduled: 28th of March)

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#57]
Joint effort between Stephen and Jørn/Henriette. Related to issue #26

**Comment by FritzdorfSport** [comment]
This Thursday? (21st March)

Next week? Wednesday or Thursday 27/28 March at any time, or Friday 29th in the morning?

**Comment by frksteenhoff** [comment]
> This Thursday? (21st March)
> 
> Next week? Wednesday or Thursday 27/28 March at any time, or Friday 29th in the morning?

Hi Stephen, 

I just talked to Jørn.
For us the 27th or 28th would be best.

* The 27th before 12.00
* The 28th is more free.

What would suit you?  -- and how long do you think it will take?

**Comment by FritzdorfSport** [comment]
Let's do the 28th. I have put the whole day aside for ClimApp work.

Over the next few days I/we can work out exactly what we do with the time, and how much time is needed, but for now should we pencil in a 0900 start?

**Comment by frksteenhoff** [comment]
Deal! 👍

**Comment by Chuansi-LU** [comment]
Great! By the way, we will have student heat lab exercise at 50 C on 27-28 March in Lund. There are 21 students attending Human Performance in Extreme Environments course.

**Comment by FritzdorfSport** [comment]
Great! See you next Thursday.

Where?

My phone: +46702030968

**Comment by frksteenhoff** [comment]
Perfect, I think we were expecting a Skype meeting, but otherwise building 402 at DTU (Danmarks Tekniske Universitet (DTU) Nils Koppels Alle, Bygning 402) is also a possibility.

**Comment by FritzdorfSport** [comment]
I think we'd get more from it face-to-face, and I am curious about your workplace ;-)

I'm very happy to come over to DK
