### ISSUE TITLE
Deal with technical debt

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#67]
**List of suggestions:**

* [x] All functionality is added in `index.js` would be better to split the different concerns to make it easier to change later.
* [x] Add `platform` folder to `.gitignore` file -- not needed to include with every commit as or build will be individual base on platform. Will only pollute the codebase. (i recommmend following [this guide](http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/) after adding `cordova/climapp/platforms*` to `.gitignore`.
* [x] Add `node_modules` to `.gitignore` all modules are kept track of in `package.json` and it is better not to pollute the branch with this large amount of data.
* [ ] Add the old Android content `Github/ClimApp/ClimApp` to ´.gitignore` (minimize code in repository + cleaning up) **currently not prioritized, not code-related**
* [x] How do we handle situations without internet connection? (to ensure a good user experience)
* [x] It would be nice to actually show the option chosen for `unit of measurement` on the settings page -- this makes it more intuitive and shows that the correct setting has taken effect.
* [x] Timeout for updating location of 30s? Decrease timeout, will result in a bad user experience?
* [x] Add color to navigation bar. Makes it easier to distinguish content and fixed displays.
* [x] Use https rather that http for climapp database on DTU. (Henriette working with DTU IT to get it fixed)
   * Traffic on 443 opened (Henriette need to migrate all logic)
* [x] Handle situation where location response is `{}` otherwise the dashboard will just not update. Give some response about trying to update/just do an update.

**Comment by BorisKingma** [comment]
yes, good point, I assigned it to myself.

after this weeks release we'll fix this

**Comment by frksteenhoff** [comment]
Closing, last point not prioritized.
