### ISSUE TITLE
Create basic layout for website

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#7]
Should we have a website, something like "https://www.climapp.com"?

**Comment by Chuansi-LU** [comment]
Good question. Sorry I did not notice this question earlier. It would be nice if there is an email notification when there a question/issue/helpneeded in GitHub. 

Can you use Project website http://www.lth.se/climapp/ ?

**Comment by Chuansi-LU** [comment]
We have similar issues in Yammer. Discussions in Yammer were not noticed by some partners (they did not log into Yammer). Sometimes partners get an email reminder, but not always.

**Comment by frksteenhoff** [comment]
Hi Chuansi it will require a lot of extra work for me to add my concerns in several places. I think we should figure out what is best to do, but for now I will continue here and if I think it is relevant I will bring it up for everyone 😄

**Comment by Chuansi-LU** [comment]
Hi Henriette,
I am in Croatia attending PPTR conference. Lars returned yesterday. We presented ClimApp a couple of times. A number is audiences are interested. They are also spreading it via their network. We may soon get moe users to install ClimApp. There are also comments and issues to be solved, for example when it is 17 C, cloudy, medium work intensity, normal clothing , WBGT should not reach alert level (red code).

WBGT is a screening tool. For more detail analysis of hot environments, we need PHS that can calculate sweat rate (water loss, hydration level) and core body temperature prediction.

Best
Chuansi

On 12 Oct 2018, at 10:12, Henriette Steenhoff <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Chuansi it will require a lot of extra work for me to add my concerns in several places. I think we should figure out what is best to do, but for now I will continue here nad if I think it is relevant I will bring it up for everyone.

**Comment by frksteenhoff** [comment]
Hi again Chuansi, 

This error is corrected in my latest release -- it will be in effect on Google Play from tomorrow. As this comment does not have anything to do with this issue I will move its content to the actual issue number and hide it from here.

**Comment by FritzdorfSport** [comment]
The website at http://www.lth.se/climapp/ is a good one for academics, and while the project is running (although there is a problem with the front page - see attachment).

But it is not the one for users. This is a question for the legacy, and is tied in with the question about what happens when the 3 years is up - who/how is the App managed?
![Screenshot 2019-03-19 at 11 21 28](https://user-images.githubusercontent.com/10878963/54599271-929f9000-4a3a-11e9-989e-9afe135c6e51.png)

**Comment by Chuansi-LU** [comment]
Good questions. We should have discussed this question during last consortium meeting in Lund. Hope there will be opportunities to discuss these issue in Brussels in September when all 26 project coodinators meet. It is good to have a website for users, and linked to present website (http://www.lth.se/climapp/). By the way, the layout problem has just been corrected. Another way is to continue to apply for EU Projects associated with ClimApp.
