### ISSUE TITLE
Scaling error when switching from portrait to landscape mode (see attached images)

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#78]
**Portrait (OK)**

![image](https://user-images.githubusercontent.com/6978512/55067023-3e6e5e80-507f-11e9-9b23-6b49cb35537b.png)

**Landscape (OK)**
![image](https://user-images.githubusercontent.com/6978512/55066816-da4b9a80-507e-11e9-93aa-d56cc9139229.png)

**When switching back to portrait (error)**
![image](https://user-images.githubusercontent.com/6978512/55066848-ee8f9780-507e-11e9-8a46-c51828fde5bb.png)

**Comment by BorisKingma** [comment]
let's only use portrait mode.

**Comment by BorisKingma** [comment]
we can arrange that in the config.xml

**Comment by frksteenhoff** [comment]
Scaling is fixed in newer version of app, problem does not occur anymore.
