### ISSUE TITLE
Find appropriate clothing icons for app

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#8]
Need clothing images, clo-values etc. for all clothing that is needed in the basic version of the app.

**Comment by Chuansi-LU** [comment]
We (manly Kalev) have been working on this. Kalev sent an email  including clothing matrix to you and Jörn on 7th of June. The matrix is developed based on ISO standard 9920. More discussions and improvements are needed.

**Comment by frksteenhoff** [comment]
Before I can implement anything I might need more than just an ISO standard I hope we can discuss this at our next meeting if not before.

**Comment by Chuansi-LU** [comment]
I suggest that you and Kalev schedule a meeting to implement the clothing matrix. Kalev has pepared an excel file (sent by email) and explained in his deliverable report D1.5.
