### ISSUE TITLE
remove appid from code, retrieve it from other source

### ISSUE THREAD

**Issue by BorisKingma** [frksteenhoff/ClimApp#86]
the openweather appid key is now visible in code.

as the app  (.apk or .ipa) could be reverse engineered, we need to find an alternative where we retrieve the appid from a service, so it is available in memory, but not hardcoded in source.

Proposal: use UUID as key to retrieve openweather appid from DTU server?

**Comment by frksteenhoff** [comment]
Definitely a possibility. I will look into it.

**Comment by frksteenhoff** [comment]
Handled in commit 3084193710d229108a5d36f51a4a3e21a4df1e43
