### ISSUE TITLE
hasExternalDBRecord logic

### ISSUE THREAD

**Issue by BorisKingma** [frksteenhoff/ClimApp#95]
Check this logic please. Is there a dependency that should be synchronized?

On my android device, and iOS emulater this part fails about 50% of the time, that is why I assume it is a synchronization issue.

**Comment by frksteenhoff** [comment]
I think I found the error -- after moving some functionality out of `index.js`, the knowledgebase was not updated correctly, which I am correcting in my latest commit 6101c44cb1078b6ab2df6a0e2a12515e7d7feb92. Please reopen if problem persists
