### ISSUE TITLE
feedback error on line 10 

### ISSUE THREAD

**Issue by BorisKingma** [frksteenhoff/ClimApp#98]
Error: TypeError: undefined is not an object (evaluating 'kb.user_info.dtu_ip') in file:///Users/boriskingma/Library/Developer/CoreSimulator/Devices/84E0B49B-5350-408E-B59A-4DBD5B15FC95/data/Containers/Bundle/Application/19C1710D-66B6-4663-9676-51F04C9FF8AD/ClimApp.app/www/js/helper_functions/dtu_database.js at line 10

**Comment by frksteenhoff** [comment]
Sure you cleared the knowledgebase? Otherwise it will not be updated? -- and it does exist.
When does this happen for you? I need some context to replicate the error.

**Comment by frksteenhoff** [comment]
Fixed with commit: 9549e86561491cc916dfeaaf6db82d2c5cb94888 
Passed wrong object to function.
